version: '3.8'
services:
  api:
    container_name: brasilprev-api
    build:
      context: ./
      target: deps
      dockerfile: Dockerfile
    command: npm run migrate:deploy && npm run start:dev
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://brasilprev:brasilprev@brasilprev-postgres:5432/brasilprev
    ports:
      - 3333:3000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped

  postgres:
    container_name: brasilprev-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=brasilprev
      - POSTGRES_USER=brasilprev
      - POSTGRES_PASSWORD=brasilprev
    ports:
      - 5432:5432
    restart: unless-stopped